Anankke/SSPanel-UIM

- config/.config.php.example
> 修复配置文件导致500错误

- app/Command/XCat.php
- app/Controllers/Admin/NodeController.php
- app/Controllers/AdminController.php
- app/Controllers/UserController.php
- config/.config.php.example
新增：
【1】
一键迁移/更新配置，使用命令：
php /网站目录/xcat migrateConfig
省去了每次更新之后都要自己手动更新config的麻烦
迁移/更新之前会自动备份原config为.config.php.bak
【2】部分输入增加了输入检查，输入小数的时候会提示“非法请求”
修复：
置空IP时，无法正确获得IP地址的BUG
如果因本次更新出现BUG，请联系
[QQ2576479186]或
[邮箱soda_mail@qq.com]或
[魔改修改版官方TG群@The_DeIc ]
> 新增一键迁移/更新配置

- resources/views/material/user/nodeajax.tpl
> 服务器ULDL速度->直观的ULDL速度

- resources/views/material/auth/login.tpl
- resources/views/material/user/code.tpl
- resources/views/material/user/doiam.tpl
- resources/views/material/user/edit.tpl
- resources/views/material/user/nodeinfo.tpl
Replace all of `jquery.qrcode` and its function with `qrcodejs` one.
This PR is related to issue #373, and may contains BREAKING CHANGES.
> Refactor: remove jquery.qrcode

- app/Utils/Hash.php
刚刚开发环境实践了一下
由于直接Argon2字符超过64位数据库装不下，懒得去改数据库结构了，所有再套一层sha256在外面缩短下长度
> sha256 + argon2

- app/Controllers/Admin/RelayController.php
- app/Controllers/RelayController.php
修复如果端口设置为0或者为空的情况下，(默认逻辑是监听443 的配置缺失的问题）
> 修复端口为0或者空造成的中转问题

- app/Utils/Tools.php
紧急修复了原先的二逼bug，
1. 修复端口设置为0或者为空的时候不按照之前规则，自动切换成443的订阅的bug
> 修复端口设置为0，本地监听时候，订阅端口不切成0的bug

- app/Utils/Tools.php
- resources/conf/clash.tpl
1. 修复了在smarty template中使用append时候，因为规定了index =0，造成第一个代理被替换的bug
> 修复Clash完整订阅中Auto覆盖第一个代理的bug

- .gitignore
- .travis.yml
- test/listTpl.sh
Although th [smarty-lint](https://github.com/erunion/smarty-lint) added in this PR is such an antique, it is still usable at this moment.
If someone want to rewrite the `smarty-lint`, just fork the origin `smarty-lint` repo.
> feat/ci: add smarty lint & npm audit to ci

- config/routes.php
闲了想写个功能，结果发现本地运行php7.2 or 7.3 均无法进入index，第一时间往回切commit，本地部署发现没有问题
第二时间定位bug发现字段$debug不认，对比发现改成全局DEBUG字段这里少改了一行？
不知道大佬是怎么本地调试开发的，我是phpstorm2019.2.1的build-in web + php7.3，本地报错
config文件里
`$System_Config['debug'] =  false;								//正式环境请确保为 false`
不管是false和true都没用
恕我表达能力欠佳，还是贴个图好了
- 发现bug时
- 修改字段后
> fix: 修复不能识别$debug字段, 本地开发环境无法进入index的bug

- src/Controllers/Mod_Mu/UserController.php
Hi there~
I've implemented an v2ray-server, [v2ray-poseidon](https://github.com/ColetteContreras/v2ray-poseidon/wiki/00-%E5%85%AC%E5%91%8A%E5%92%8C%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v120), which can limit users simultaneous online IP count accurately. ONLY one way to get the amount is by API
Thanks~
> Add node_connector for users api

- resources/views/material/auth/login.tpl
- Use inputmode="numeric" for better iOS experience
- Use autocomplete="one-time-code" for Safari/Chrome support
> feat(login): better 2fa solution

- src/Utils/Telegram/Commands/SetuserCommand.php
1. 修复任意人员都可以admin修改的问题
2. 提醒，如果需要非管理员回复，请配置$_ENV['enable_not_admin_reply'] = true && $_ENV['not_admin_reply_msg']="xxxxx"
3. 升级过程中 config.example.php 和 appprofile.example.php 记得抄一下 感恩
#980
> 修复新bot的管理员权限bug

- src/Command/Job.php
- src/Utils/Tools.php
int max : 2147483647
解决超级机场日志 ID 超过 MySQL INT 最大值的问题。
> feat(sql): reset auto_increment

- config/appprofile.example.php
- src/Controllers/ConfController.php
解决QUIC模式下，因DNS解析问题导致的ERR_QUIC_PROTOCOL_ERROR问题，解决方案是向配置文件中添加dns配置区块，指定DNS服务器。
遇到的实际问题：在最新版的 Clash for Android 上访问 www.google.com 报错 `ERR_QUIC_PROTOCOL_ERROR`，但是却能正常访问 www.google.com.hk、www.youtube.com 等网站，相关报告见这个issue：https://github.com/Kr328/ClashForAndroid/issues/624
> Add DNS field to Clash configuration

- resources/views/material/404.tpl
- resources/views/material/405.tpl
- resources/views/material/500.tpl
- resources/views/material/doc/index.tpl
- resources/views/material/indexold.tpl
- resources/views/material/staff.tpl
- resources/views/material/telegram_error.tpl
- resources/views/material/telegram_success.tpl
- resources/views/material/tos.tpl
部分页面已有声明页面语言，但大部分没有
此次 PR 的目的皆在为默认 material 主题统一增加页面语言声明，以解决在非中文浏览器环境下浏览部分未声明语言的页面，默认调用非中文字体的情况，影响阅读
> 统一声明页面语言标签

- src/Command/Job.php
仅提取最新的可重置购买记录做重置匹配，避免多购买，单月多重置的bug
> 修复查询多个购买记录重置流量的bug

- src/Models/Node.php
AEAD单端口多用户无需协议混淆支持,设置承载用户时 协议设为"origin", 混淆设为"plain"即可支持AEAD单端口类型, 届时密码不再为单端口承载用户密码,故作此改动.
> Support Shadowsocks AEAD multiuser in a port

- src/Utils/AppURI.php
修复了不标准的 v2rayN 订阅链接，[标准格式](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))
~~主要是适配 Netch 1.8.0~~
> Fix non-standard v2rayN subscription links.

- src/Utils/AppURI.php
https://github.com/paradiseduo/ClashXR/issues/24
```
Clash的SSR新参数与ClashR参数的区别在于 protocolparam 和 obfsparam 的不同
ClashR是「protocolparam」和「obfsparam」
Clash新参数是「protocol-param」和「obfs-param」
```
> clash 已经支持ssr 了

- src/Utils/AppURI.php
增加sni参数并使用host作为sni，防止在surge使用vmess tls节点时，由于节点证书与节点域名不一致导致的证书错误
> 为surge节点增加sni参数

- src/Utils/AppURI.php
支持clash Shadowrocket v2rayn 的sni证书功能
使用方法：节点地址 末尾添加 "|sni=证书域名"
如节点保存错误，是因为节点地址长度过长超过了默认的128字节导致的
数据库 执行
ALTER TABLE ss_node CHANGE server server VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
> 为vmess增加sni分流支持

- resources/views/material/user/index.tpl
应用面板增加 Stash for iOS 支持；
Stash 是一款 iOS 平台基于规则的多协议代理客户端，完全兼容 clash 配置，支持 Rule Set 规则、按需连接、SSID Policy Group等特性.
App Store 链接：https://apps.apple.com/app/stash/id1596063349
> feat: add Stash for iOS

- src/Utils/AppURI.php
> 恢复clash的旧版格式，使其并行

- src/Utils/Tools.php
- src/Utils/URL.php
很多人还在使用把参数写在节点地址server[5]的方式，在commit：https://github.com/Anankke/SSPanel-Uim/commit/8d677b61aed5420686f9f9dbfbebe16bd7d1c481 将v2ray中的全部parseArgs改为custom config会导致很多path下发为“/”的问题：
- https://github.com/Anankke/SSPanel-Uim/issues/1497
- https://github.com/Anankke/SSPanel-Uim/issues/1517
> Add back parseArgs to fix bug

- resources/views/tabler/admin/setting/email.tpl
email.tpl 中存在问题，导致80和443端口都显示为2525，而实际无法设置为2525端口。
> Fix email.tpl error

- resources/views/tabler/admin/announcement/index.tpl
- resources/views/tabler/admin/coupon.tpl
- resources/views/tabler/admin/detect.tpl
- resources/views/tabler/admin/giftcard.tpl
- resources/views/tabler/admin/node/index.tpl
- resources/views/tabler/admin/order/index.tpl
- resources/views/tabler/admin/product/index.tpl
- resources/views/tabler/admin/ticket/index.tpl
- resources/views/tabler/admin/user/index.tpl
- resources/views/tabler/user/edit.tpl
- Change all .on('click') to .off('click').on('click') 
Change all `.on('click')` to `.off('click').on('click')` for proper event unbinding and to prevent issues with duplicate event handlers.
`.on('click')` 调用后没有解除绑定，也没有刷新页面，因此会导致下一次进行同样操作的时候出现发送以前和现在的全部请求。因此使用 `.off('click')`解除绑定。
此问题导致曾经的实际可感知的影响应该为前端（节点、产品）的时候，连续复制会出现问题，其他删除、停用因为在重复发送ajax请求的时候已经操作过了，所以可能没有被感知。
- 修改 edit.tpl
由于 `/user/telegram_reset` 不支持GET方式，因此使用AJAX进行解绑处理。
> Change Telegram unbind button and  change all .on('click') in ajax to .off('click').on('click') 

- src/Utils/Tools.php
传入奇数长度时会导致除以2结果为小数，产生以下报错
`openssl_random_pseudo_bytes(): Argument #1 ($length) must be of type int, float given`
解决方案：向上取整再截取字符串
> fix: unable to pass odd number to genRandomChar

- config/appprofile.example.php
sing-box很奇怪的故障，经测试 DNS Server `"address": "",` 使用域名且 `"address_resolver": "",` 正常配置的情况下，dot/h域名只能正常使用 DNSPod 系（如`dns.pub` `dot.pub`）的域名，其他家的dot/h服务（如`cloudflare` `google` `alidns`）域名（能解析到dot/h服务对应的IP）都无法使用解析服务（但直接使用dot/h服务 `IP` 可以正常使用解析服务）
> [Uim] Add Rule (for ipv6)

- config/appprofile.example.php
- src/Services/Subscribe/Clash.php
- src/Services/Subscribe/SingBox.php
> [Uim] (update)sing-box rule
