Anankke/SSPanel-UIM

app/Controllers/Admin/ShopController.php, app/Models/Shop.php, resources/views/material/admin/shop/edit.tpl
1.修复商品端口限速和IP限制不能解除的bug
2.修改admin编辑商品不能获取商品端口限速和IP限制数据的bug
=> 修复商品端口限速和IP限制的bug

config/.config.php.example
=> 整理.config.php

app/Controllers/AuthController.php, app/Controllers/UserController.php, resources/views/material/auth/register.tpl, resources/views/material/user/invite.tpl, resources/views/material/user/main.tpl
1，enable_invite_code为true则注册必须要填邀请码；
2，邀请人等级为0则邀请码不可用；
3，邀请人invite_num为可邀请次数，填负数则为无限
=> 为面板增加 AFF 功能

resources/views/material/404.tpl, resources/views/material/405.tpl, resources/views/material/500.tpl, resources/views/material/admin/footer.tpl, resources/views/material/admin/main.tpl, resources/views/material/code.tpl, resources/views/material/footer.tpl, resources/views/material/header.tpl, resources/views/material/index.tpl, resources/views/material/staff.tpl, resources/views/material/tos.tpl, resources/views/material/user/footer.tpl, resources/views/material/user/header_info.tpl, resources/views/material/user/index.tpl, resources/views/material/user/main.tpl
Bring up using jsdelivr public cdn for better performance.
=> feat: bring up cdn support

app/Controllers/Admin/NodeController.php, app/Controllers/Mod_Mu/UserController.php, app/Controllers/UserController.php, app/Models/Node.php, app/Models/User.php, composer.json, composer.lock, config/.config.php.example, resources/views/material/admin/node/create.tpl, resources/views/material/admin/node/edit.tpl, resources/views/material/user/node.tpl
=> V2ray support 

.gitignore, app/Controllers/UserController.php, resources/views/material/user/node.tpl
fix: fix nodeLoad error if no value
=> fix: fix v2ray display

app/Controllers/LinkController.php
{$baseUrl}/link/{$ios_token}?is_ss=1
注意：必须开启 obfs，兼容 Surge2 / 3
自动更新节点+规则
顺便修复了 ss-libev conf 文件
=> 增加 Surge 托管（lhie1.conf）

app/Controllers/AuthController.php, resources/views/material/auth/login.tpl
Use assign in Controller instead of Smarty to avoid potential issue
=> Oauth Frontend Ready

app/Command/Job.php
=> 修复面板备份功能漏掉数据库中的易付通表

app/Utils/TelegramProcess.php
Optimize the prompt that will trigger the reply no matter what.
=> Optimize Reply Tips.

app/Command/XCat.php, app/Controllers/Admin/CodeController.php, app/Controllers/AdminController.php, app/Controllers/UserController.php, app/Utils/Tools.php, resources/views/material/user/code.tpl, resources/views/material/user/edit.tpl
=> 完成ajax局部刷新

app/Controllers/Admin/UserController.php, resources/views/material/admin/user/edit.tpl
=> 加了个二次验证的开关

app/Controllers/Admin/NodeController.php, app/Controllers/AuthController.php, app/Controllers/UserController.php, resources/views/material/email_nrcy.tpl, resources/views/material/user/code.tpl, resources/views/material/user/index.tpl
优化充值界面，trim优化输入（再也不用怕因为多输入空格导致各种错误了）
=> 优化充值界面，trim优化输入

resources/views/material/admin/user/index.tpl
=> 可在用户列表切换用户

resources/views/material/user/edit.tpl
=> Fix a typo

resources/views/material/password/reset.tpl
=> 修复重置密码页回车键无法提交

app/Command/Job.php
节点自动获取IP只有当节点地址不为IP时才处理，减少处理次数，优化大站处理效率
=> 【1024节点必备】优化节点地址解析

app/Controllers/AdminController.php, config/routes.php, resources/views/material/admin/find.tpl, resources/views/material/admin/main.tpl
=> 增加用户快速搜索编辑删除

public/404.html, resources/views/material/404.tpl, resources/views/material/405.tpl, resources/views/material/500.tpl, resources/views/material/footer.tpl, resources/views/material/index.tpl, resources/views/material/staff.tpl, resources/views/material/tos.tpl, resources/views/material/user/footer.tpl
Add jsDelivr public cdn support for those lib:
- jquery@1.11.3
- jquery@2.2.1
- ajlkn/sekl@3.0.1
- canvas-nest@1.0.1
=> Feat: add public cdn support for javascript lib

resources/views/material/user/footer.tpl
=> 本地加载qrcode.min.js

resources/views/material/admin/main.tpl, resources/views/material/header.tpl, resources/views/material/user/header_info.tpl, resources/views/material/user/main.tpl
- Feat: reduce google fonts requests
- Fix: bring up missing jsDelivr for dataTables css & `material.css`
=> Some minor changes

app/Controllers/AuthController.php, app/Controllers/UserController.php, config/.config.php.example, resources/views/material/auth/login.tpl, resources/views/material/auth/register.tpl, resources/views/material/user/index.tpl
A faster, more convenient captcha widget. And it also can be used in China.
=> add: reCAPTCHA

app/Controllers/AuthController.php, app/Controllers/UserController.php, config/.config.php.example, resources/views/material/auth/login.tpl, resources/views/material/auth/register.tpl, resources/views/material/user/index.tpl
=> re: add: reCAPTCHA

app/Controllers/UserController.php, resources/views/material/auth/login.tpl, resources/views/material/auth/register.tpl, resources/views/material/user/index.tpl
=> fix: complete reCAPTCHA(?

app/Utils/URL.php, resources/views/material/user/nodeinfo.tpl
see also [shadowsocks-libev#2189](https://github.com/shadowsocks/shadowsocks-libev/issues/2189)
=> fix shadowsocks json

app/Command/XCat.php, app/Models/User.php, app/Utils/TelegramProcess.php
=> add bot订阅信息回复

app/Command/XCat.php, app/Models/User.php
由于用户删除tg ID或者用户屏蔽，或者stop了bot情况，做了异常处理
=> 增加sendDailyUsage代码部分对无法找到chat的异常处理

app/Utils/TelegramProcess.php
=> 增加tg bot 重置订阅链接功能

.travis.yml
- Cache composer and node_modules
- Remove useless apt update
- Remove log output
=> Feat: speed up CI

app/Command/Job.php, app/Controllers/Admin/NodeController.php, app/Controllers/Admin/RelayController.php, app/Controllers/Mod_Mu/FuncController.php, app/Controllers/Mod_Mu/NodeController.php, app/Controllers/Mu/UserController.php, app/Controllers/RelayController.php, app/Controllers/UserController.php, app/Utils/Tools.php, app/Utils/URL.php, resources/views/material/admin/node/create.tpl, resources/views/material/admin/node/edit.tpl, resources/views/material/user/node.tpl
1.增加了我的后端的v2ray中转配置，和一个Caddy tls监听的逻辑。
2.修复了一个v2ray订阅v2rayN中缺少add的字段的问题
=> 增加对Rico的V2ray后端中转和Caddy监听的适配

app/Controllers/Admin/UserController.php, config/routes.php, resources/email/newuser.tpl
目前只是尝试写了post api，前端没有写。
Post Api 这里参考着注册和购买套餐的代码写了两个函数。 
createNewUser 这里需要 从request里面得到userEmail的值，成功的生成，会尝试给这个邮箱发送账号和随机生成的密码。
buy 需要 从request里面得到shopId，disableothers，autorenew,userEmail 这四个key的值。 然后shop的信息我这里没重写，可以用 App\Controllers\UserController:shop来获得
=> 增加管理员添加用户和添加套餐的post api

app/Command/Job.php
=> 修改if判断代码风格

app/Services/Gateway/SPay.php, config/routes.php
=> 临时修复spay支付

app/Controllers/Admin/AnnController.php, app/Controllers/UserController.php, config/.config.php.example, resources/views/material/admin/announcement/create.tpl, resources/views/material/user/ticket_create.tpl, resources/views/material/user/ticket_view.tpl
=> 一些手残和BUG修正

app/Models/Shop.php, config/.config.php.example
=> 增加延长等级期限功能

app/Command/Job.php, config/.config.php.example
增加节点掉线后推送至Server酱
本人已反复测试 tg一发 Server酱微信就发来了
=> 增加节点掉线后推送至Server酱

app/Controllers/Admin/AnnController.php, resources/views/material/admin/announcement/create.tpl
不过话说一时CTRL+C/V一时爽，一直CTRL+C/V 修起BUG火葬场
=> 修复无脑CTRL+V

.travis.yml, test/config.php, test/travis-ci.conf
Problem caused by permission issue.
Solution: `sudo adduser www-data travis`
Ref: https://github.com/Nebo15/gandalf.api/blob/master/.travis.yml#L32
=> fix/ci: nging 404 error

resources/views/material/user/edit.tpl
=> [BREAKING CHANGES] Filter for SS/SSR in user/edit pages

app/Services/Gateway/PAYJS.php, app/Services/Payment.php, config/.config.example.php, resources/views/material/user/payjs.tpl
=> 增加PayJs支付方式（微信支付)

app/Utils/TelegramProcess.php
Different variable parameters in "needbind_method" function.
Different variable parameters in "telegram_process" function.
=> fix: bot does not respond.

app/Utils/TelegramProcess.php
=> refactor(TelegramBot): Optimization Event listener

app/Controllers/Client/ClientApiController.php
* 修复暴力获取mu参数引发的错误。
* 简单优化没有mu参数的逻辑。
=> #801 修复暴力获取mu参数引发的错误。

resources/views/material/user/index.tpl
=> fix error(user/index): rm obsolete code

app/Controllers/AdminController.php, config/routes.php, resources/views/material/admin/invite.tpl
有时候用户会反馈邀请了人 可是对方并没有归于自己邀请之下 （各种原因aff没有成功）
于此添加一个方便更改用户的邀请者功能
=> 添加更改用户邀请者的功能

app/Models/User.php, resources/views/material/admin/code/index.tpl
Re-submission from previous PR.
=> Add display income feature

app/Models/User.php, resources/views/material/admin/user/index.tpl
Add feature to display amount of paid users in /admin/user
=> Add paid user count feature

app/Models/User.php, resources/views/material/user/disable.tpl
Add feature to display disable reason at /user/disable
=> Add function to display disable reason for disabled accounts

resources/views/material/user/nodeinfo.tpl
Add feature to copy SS/SSR link for specific node in one button
=> Add copy button for node SSR and SS link

resources/views/material/user/index.tpl
=> 修复安卓V2RayNG链接错误

app/Models/User.php
Fix bug as mentioned by @topjohncian
=> Fix bug for income calculation

app/Models/User.php
=> Simplify if...else statement from previous commit

app/Models/User.php
Ref: https://stackoverflow.com/questions/19727274/strtotime-bug-when-using-1-month-from-january
=> Fix bug: display last month Income

app/Controllers/Admin/UserController.php, resources/views/material/admin/user/index.tpl
1. missing obfs_param data in file "index.tpl"  make user list can't display
2. missing obfs_param data in file "UserController"  make DataTables warning: table id=table_1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
3. code format
=> fix(user) Fix missing obfs_param data

config/.config.example.php
Change some variables which will cause crashing when some other variables are not provided with correct value.
避免小白搭建失败了来逼逼
=> Change some variables to false

app/Controllers/Mod_Mu/UserController.php, resources/views/material/user/node.tpl
=> Address Multi-User issue

.travis.yml, uim-index-dev/src/App.vue
修改后环境能安装了，代码跑不过去，存在一个未使用的定义引用
```bash
error: '_get' is defined but never used (no-unused-vars) at src/App.vue:67:10:
```
https://github.com/Anankke/SSPanel-Uim/blob/ed11b5e63b048ab95405ce29c2b56c5e2463a986/uim-index-dev/src/App.vue#L67
=> fix(travis): 暂时不使用 Sukka 源

sql/clean_job.sql, src/Command/Job.php, src/Models/Bought.php, src/Models/Node.php, src/Models/User.php, utils/clean_job.php
=> clean Job file database

config/.config.example.php, src/Services/Mail/SendGrid.php
邮件没有发件人名称总是看着比较诡异……
详见 #910 
For Dev Branch
=> Sendgrid添加发件人名称

src/Controllers/Admin/RelayController.php, src/Controllers/RelayController.php
=> fix bug: 链路表!

config/.config.example.php, src/Controllers/Mod_Mu/UserController.php, src/Controllers/UserController.php, src/Utils/Tools.php
1. 增加缺失 环境变量 keep_connect
2. 删去多余的 环境变量 user_agreement_scheme
3. 兼容单多承载没有按照 geek的端口偏移填写规范来的 bug
4. 增加对node_id的key是否存在的bug判断的补丁(有些丑）
=> 修补geek新pr的几个小问题

resources/views/material/auth/login.tpl
https://github.com/Anankke/SSPanel-Uim/blob/e76d45fd0ffac7fad74ac8c86da3f8fc2706ef88/resources/views/material/auth/login.tpl#L34
此处没有必要让浏览器记录填写内容。
=> 禁用“两部验证码”表单自动填充

resources/views/material/auth/login.tpl
Reverts Anankke/SSPanel-Uim#973
We have a better way to do that.
=> Revert "禁用“两部验证码”表单自动填充"

resources/views/material/user/index.tpl, src/Utils/Telegram/Callbacks/Callback.php
1. Callback修改User的配置顺序
2. index.tpl 渲染时候针对key是否存做判断
=> 针对miku的issue， 的第一个 index问题

src/Models/Bought.php
=> feat: 精确计算重置时间

src/Controllers/VueController.php
=> 修复Vue返利信息展示

resources/views/material/auth/login.tpl, resources/views/material/auth/register.tpl, resources/views/material/password/reset.tpl
=> feat: better input solution

src/Command/Update.php
=> feat: auto add columns

src/Utils/AppURI.php
=> 订阅链接兼容现有trojan客户端

resources/views/material/user/node.tpl
=> 添加trojan://单个链接生成，支持导入到shadowrocket等软件

resources/views/material/user/node.tpl
=> 兼容 Trojan-QT5

resources/views/material/user/node.tpl
=> 优化Trojan订阅链接

resources/views/material/user/index.tpl
更新 Shadowrocket 使用方式为一键导入 Shadowrocket 和拷贝订阅链接
=> 更新 Shadowrocket 使用方式为一键导入 Shadowrocket 和拷贝订阅链接

resources/views/material/auth/telegram.tpl, resources/views/material/user/aopf2f.tpl, resources/views/material/user/bitpay.tpl, resources/views/material/user/bitpayx.tpl, resources/views/material/user/chenPay.tpl, resources/views/material/user/payjs.tpl, src/Services/Gateway/TomatoPay.php
=> feat(js): 更正 JS 轮询逻辑问题

config/.config.example.php
#1035 config example : xcat hints update
=> Update .config.example.php ( #1035 )

src/Models/User.php
=> Fix: 陈年我写的旧bug（计算收入）

src/Command/Job.php
=> fix(notices):优化余量不足检测逻辑

app/container.php, composer.json, config/.config.example.php, public/index.php, resources/views/material/500.tpl, src/Services/Boot.php, src/Services/Config.php, xcat
cleanup and fix error handling shit,
optimize autoloader,
add sentry integration for production debugging
=> refactor: error handling

src/Command/Job.php
Avoid potential conflict during `git pull`.
=> feat(ssr-download): add --rebase param to git pull

resources/views/material/admin/ip/alive.tpl, resources/views/material/admin/ip/block.tpl, resources/views/material/admin/ip/login.tpl, resources/views/material/admin/ip/unblock.tpl
=> feat(admin/ip): ip geolocation finder

resources/views/material/admin/index.tpl
=> Admin后台主页添加用户和收入总览

README.md
麻烦各位大佬看看 API 文档还有什么需要补充的吗，这个是根据 Vue 版页面写的，其它 API 因为只有 MPA 页面有，而且是服务端渲染的所以我就获取不到了。
=> 更新 API 文档为新版本

config/.config.example.php, sql/glzjin_all.sql, src/Command/Job.php, src/Controllers/Admin/AnnController.php, src/Models/EmailQueue.php, src/Models/User.php
邮件队列真好
万人机场不卡checkjob
需要每分钟执行 php xcat Job SendMail
=> Add Mail Queue

sql/glzjin_all.sql, src/Command/Job.php, src/Controllers/LinkController.php, src/Controllers/UserController.php, src/Controllers/VueController.php, src/Models/Link.php, src/Utils/Telegram/Callbacks/Callback.php, src/Utils/TelegramProcess.php, utils/clean_link.php
- 修邮件队列定时任务
- 清理 link 表历史遗留
更新后手动执行一次 `php /xxx/sspanel/utils/clean_link.php`
=> 清理 link 表历史遗留 && 修邮件队列定时任务

config/appprofile.example.php
=> surge4  only http

src/Command/Job.php
- 提取shop内带重置套餐
- 匹配bought内用户最新购买的带重置套餐
NOTE: 先勿同意，等测试可行再审核
#TesterWelcome
=> 重写重置流量提取逻辑

src/Utils/AppURI.php
QuantumultXUR ss tls 无obfs-uri=/ 参数 
见第167 170 行
=> FIx QuantumultXUR

resources/views/material/user/index.tpl
将ss订阅链接按钮添加到首页
https://github.com/Anankke/SSPanel-Uim/issues/1204
=> Add Shadowsocks sub link to index

resources/views/material/user/node.tpl
Issues here: https://github.com/Anankke/SSPanel-Uim/issues/1246
=> fix mu_port node detail can't display

src/Utils/URL.php
Issues listed here: https://github.com/Anankke/SSPanel-Uim/issues/1261
=> Fix can't copy All SS URL under AEAD Ciphers

config/.config.example.php, src/Command/ClientDownload.php, src/Command/Update.php, src/Controllers/BaseController.php, src/Services/View.php
547e859 : 将用户组修改为变量，使不同的用户组也可以更好的使用 
be0e348  : 修正 SQL 查询次数
=> feat: 优化数据

src/Controllers/BaseController.php
=> fix error with #1274 

composer.json, src/Utils/Telegram/Commands/CheckinCommand.php, src/Utils/Telegram/Commands/HelpCommand.php, src/Utils/Telegram/Commands/InfoCommand.php, src/Utils/Telegram/Commands/MenuCommand.php, src/Utils/Telegram/Commands/MyCommand.php, src/Utils/Telegram/Commands/PingCommand.php, src/Utils/Telegram/Commands/SetuserCommand.php, src/Utils/Telegram/Commands/StartCommand.php, src/Utils/Telegram/Commands/UnbindCommand.php
旧版本会在 7.3 以及上环境下报错
https://github.com/irazasyed/telegram-bot-sdk/issues/679
=> update telegram sdk.

src/Utils/Tools.php
change one missing serviceName to servicename
=> fix: Change serviceName to servicename

src/Models/Node.php, src/Utils/AppURI.php, src/Utils/Tools.php
I have changed another missing serviceName to servicename.
=> fix: Change trojan serviceName to servicename

src/Utils/AppURI.php
目前vless不支持加密，此选项必须为none，选择encryption=auto会导致v2rayng无法启动vpn
=> 修正encryption

config/.config.example.php, src/Controllers/UserController.php
- 修复用户不能自主更改注册邮箱的bug
- 增加一项配置用于解决 https://github.com/Anankke/SSPanel-Uim/issues/1321
=> Bug fixes and new features

src/Models/User.php
Reverts Anankke/SSPanel-Uim#1347
=> Revert "Gravatar头像地址改为未被墙的镜像地址"

resources/views/material/admin/user/edit.tpl, resources/views/material/user/profile.tpl, src/Controllers/Admin/UserController.php, src/Controllers/UserController.php, src/Utils/Tools.php
https://github.com/Anankke/SSPanel-Uim/issues/1359
=> 修改用户信息可修改用户昵称

src/Controllers/LinkController.php
=> 正确显示Trojan类型的订阅记录

config/.config.example.php, sql/auto_backup_fix.sql, src/Command/Backup.php
Reverts Anankke/SSPanel-Uim#1375
=> Revert "Bugfix/fixAutoBackup"

src/Controllers/SubController.php
1. The node with node_bandwidth_limit = 0 should be included.
2. Some bugs for V2ray and Trojan subscription.
=> Fix bugs for universal subscription

src/Models/User.php
This reverts commit d87d5927a437c95badce93fb0e57dc3f88ca9242.
請不要濫用公益服務
=> Revert "Use gravatar mirrors to speed up access"

src/Models/User.php, src/Utils/Tools.php
https://stackoverflow.com/questions/71296583/php-8-strict-type-is-forced-on-native-function
邊用邊修吧，肯定還有很多很多地方是有問題的
=> 修正 Argument #1 ($num) must be of type int|float, string given 錯誤

.github/workflows/minify.yml
https://github.com/nizarmah/auto-minify
應該用 git-auto-commit-action@v4
=> Fix git-auto-commit-action failing in CI

public/assets/js/fuck.js
=> 解決360瀏覽器封鎖脚本在360瀏覽器上不工作的問題

src/Models/Node.php
Wiki 裏面 custom_config 參數寫的一清二楚不用，非要改原本 Working 的代碼，改又改不好，提 PR 之前也不測在 PHP8 的兼容性就推。
=> 修正PHP8環境下 Trojan/Clash 訂閲出現 “Undefined array key 1” 錯誤的問題

src/Controllers/AdminController.php
=> 修复无法添加邀请链接数量

src/Command/Tool.php
https://github.com/Anankke/SSPanel-Uim/issues/1780
=> fix: use deprecated 2fa class

composer.json, config/settings.json, resources/views/tabler/admin/setting/email.tpl, src/Controllers/Admin/Setting/EmailController.php, src/Services/Mail.php, src/Services/Mail/Postal.php
=> 增加Postal作为邮件驱动

config/settings.json, resources/views/tabler/admin/setting/email.tpl, src/Controllers/Admin/Setting/EmailController.php, src/Services/Mail/Mailgun.php
feat: Add sender name to Mailgun email
=> feat: Add sender name to Mailgun email

src/Controllers/WebAPI/UserController.php
=> fix: wrong match() statement

update.sh
This patch solves https://github.com/Anankke/SSPanel-Uim/issues/1915 （update.sh related part）
=> fix: update.sh release/dev git

src/Controllers/LinkController.php, src/Controllers/SubController.php
https: //github.com/Anankke/SSPanel-Uim/pull/2013
=> fix: subscription on clash, legacy v2ray link

config/.config.example.php, config/appprofile.example.php
=> TCP并发(Clash Meta)

config/.config.example.php, config/appprofile.example.php
=> [Uim] TCP并发(Clash Meta)

config/appprofile.example.php, src/Services/Subscribe/SingBox.php
=> fix: sing-box subscribe

config/appprofile.example.php, src/Services/Subscribe/SingBox.php
Custom Config 以启用 utls (默认 false)
~~~
"utls": true,
~~~
=> [Uim] sing-box UoT & utls

config/appprofile.example.php, src/Services/Subscribe/SingBox.php
Custom Config 以启用 utls (默认 false)
~~~
"utls": true,
~~~
=> sing-box UoT & utls

config/appprofile.example.php, src/Services/Subscribe/SingBox.php
configurable options:
for tcp(http)
```
"method": "GET",
```
for websocket(default is empty)
```
"max_early_data": "4096",
"early_data_header_name": "Sec-WebSocket-Protocol",
```
=> [Uim] (SingBox subscribe fix)Method of HTTP request

config/appprofile.example.php
New rule actions replace legacy inbound fields and special outbound fields
https://sing-box.sagernet.org/migration/
=> [Uim] for sing-box 1.11.0+

config/.config.example.php, db/migrations/2023071700-add_user_is_shadow_banned.php, src/Command/Migration.php, src/Services/Cache.php, src/Services/DB.php, tests/App/Services/CacheTest.php
Database Migrations似乎无法正常工作……
如果没理解错的话，执行顺序是 `php xcat Migration new` -> `php xcat Migration latest`
输出结果：
<details>
> root@debian:~/test/SSPanel-UIM-master# php xcat Migration new
> Found migration version 2023053000...skip
> Found migration version 2023111700...skip
> Found migration version 2023020100
> Found migration version 2024012300...skip
> Found migration version 2024041000...skip
> Found migration version 2024031700...skip
> Found migration version 2024052400...skip
> Found migration version 2023063000...skip
> Found migration version 2023111801...skip
> Found migration version 2023072000...skip
> Found migration version 2023032600...skip
> Found migration version 2024061600...skip
> Found migration version 2024012000...skip
> Found migration version 2024021900...skip
> Found …
=> fix: db migration not working

resources/views/tabler/captcha/js.tpl
=> feat: automatic captcha refresh
